ARG AIRFLOW_VERSION=2.11.0

FROM apache/airflow:${AIRFLOW_VERSION}

COPY requirements.txt /tmp/project-requirements.txt

RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /tmp/project-requirements.txt
