
name: 'dbt_finance_platform'
version: '1.0.0'

profile: 'dbt_finance_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_finance_platform:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
